#include "main.h"
#include <stdlib.h>
#include"gameCharacter.h"
#include "gba.h"

#include "images/selfMaze.h"
#include "images/lose_bec_moves.h"
#include "images/WON.h"
#include "images/character.h"
#include "images/first_image.h"
#include "images/crash.h"

/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state
{
  START,
  PLAY,
  WIN,
  LOSE,  
  STEP_01,
  LOSE_BECAUSE_MOVES,
  DEFAULT,

};


int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;

  char *string = "Moves: ";

  struct character gc;
  gc.topLeftRow = 9;

  char tens_place = '0';
  char units_palce = '0';
  char hundered_place = '0';

  struct character *gameCharacterPointer = &gc;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    switch (state) {
      case START:
        tens_place = '0';
        units_palce = '0';
        hundered_place = '0';

        waitForVBlank();
        drawFullScreenImageDMA(first_image);

        gc.topLeftRow = 24;
        gc.topLeftCol = 106;
        gc.height = 8;
        gc.width = 8;
        gc.won = 0;
        gc.moves = 0;
        gc.posChanged = 1;
        gc.lastpos = 0;
        gc.hundereds_val = &(hundered_place);
        gc.tens_val = &(tens_place);
        gc.units_val = &(units_palce);

        if (KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons)) {
          state = PLAY;
        }
        break;


      case PLAY:
        waitForVBlank();
        drawFullScreenImageDMA(maze);
        state = STEP_01;
        break;

      case STEP_01:

        if ((gameCharacterPointer -> won != -1) && (gameCharacterPointer -> posChanged ||
           (validKeyPress(currentButtons, *gameCharacterPointer))
            || KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons) 
            || gameCharacterPointer -> topLeftRow == 9) )   
        {

          if (gc.posChanged) {

            waitForVBlank();
            drawCharacter(gameCharacterPointer, gameCharacterImage);
            drawString(9, 90, string, BLUE);
            drawRectDMA(9, 128, 18, 7, WHITE);
            drawChar(9, 128, *(gameCharacterPointer -> hundereds_val), BLUE);
            drawChar(9, 134,*(gameCharacterPointer->tens_val), BLUE);
            drawChar(9, 140, *(gameCharacterPointer->units_val), BLUE);

            checkIfDie(gameCharacterPointer);
          }

          gc.posChanged = 0;

          if (gameCharacterPointer -> won == -1)
          {
            state = LOSE;
            break;
          } else if (gameCharacterPointer -> won == 1) {
            state = WIN;
            break;
          }

          if (validKeyPress(currentButtons, *gameCharacterPointer))
          { changeCharPosition(currentButtons, gameCharacterPointer);
            if (gc.posChanged) {
            if (units_palce == '9') {
              if (tens_place == '9') {
                hundered_place += 1;
                if (hundered_place == '4') {
                  state = LOSE_BECAUSE_MOVES;
                  break;
                }
                tens_place = '0';
                units_palce = '0';
              }
              else {
                tens_place += 1;
                units_palce = '0';
              }
            } else {
              units_palce += 1;
            }
            state = STEP_01;
            break;
            }
          }
          else if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons))
          {
            state = START;
          }
        }

        break;

      case WIN:
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons))
        {
          state = START;
        }
        waitForVBlank();
        drawFullScreenImageDMA(WON);
        break;

      case LOSE:
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
        }

        waitForVBlank();
        drawFullScreenImageDMA(crash);
        break;

      case LOSE_BECAUSE_MOVES:
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
          break;
        }
        waitForVBlank();
        drawFullScreenImageDMA(lose_bec_moves);
        break;

      case DEFAULT:
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
